apiVersion: v1
kind: Pod
metadata:
  name: unavailable
  namespace: fastcampus
spec:
  containers:
  - name: nginx
    image: nginxdemos/hello:plain-text
    ports:
    - name: http
      containerPort: 80
      protocol: TCP
    resources:
      limits:
        cpu: 2
        memory: 512Mi
