image: "docker.elastic.co/beats/filebeat"
imageTag: "7.16.2"

daemonset:
  enabled: true
  extraEnvs: []
  filebeatConfig:
    filebeat.yml: |
      monitoring.enabled: false
      filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log
        processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"

      output.logstash:
        host: '${NODE_NAME}'
        hosts: 'logstash-logstash:5044'

deployment:
  enabled: false
