apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sample-helm.fullname" . }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "sample-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sample-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: {{ .Chart.Name }}
        ports:
        - containerPort: 80
{{- with  .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}{{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "sample-helm.fullname" . }}
spec:
  type: NodePort
  ports:
  - protocol: {{ .Values.service.protocol }}
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetProt }}
    nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "sample-helm.selectorLabels" . | nindent 8 }}

---

{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "sample-helm.fullname" . }}
{{- if .Values.ingress.annotations }}
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "sample-helm.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end -}}