apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJmYXN0Y2FtcHVzIiwicGFzc3dvcmQiOiJmYXN0Y2FtcHVzIiwiYXV0aCI6IlptRnpkR05oYlhCMWN6cG1ZWE4wWTJGdGNIVnoifX19
