apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namePrefix: dev-

patchesJson6902:
- target:
    version: v1
    kind: Deployment
    name: hello
  path: resources.yaml
- target:
    version: v1
    kind: Service
    name: hello
  path: service.yaml
