apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-load-balancer-controller
spec:
  template:
    spec:
      containers:
      - name: controller
        args:
        - --cluster-name=apne2-fastcampus
