apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-external-secrets
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::797373241119:role/irsa-apne2-fastcampus-addon-kubernetes-external-secrets"
