replicas: 1
image:
  repository: 552661052297.dkr.ecr.ap-northeast-2.amazonaws.com/demo
  tag: 1.2.6
  imagePullSecrets:
    - name: ecr-cred
service:
  type: NodePort
  protocol: TCP
  targetPort: 8080
  port: 8080
  nodePort: 31080
ingress:
  enabled: false
