repoURL: 'https://github.com/sangwooB/fc_devops.git'
apps:
  - name: demo
    project: default
    namespace: default
    source:
      path: demo
      customValues: true
      values:
        - values-eks.yaml
