image:
  repository: amazon/aws-cli
  tag: latest
  args:
  - s3
  - ls

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: >-
      arn:aws:iam::552661052297:role/aws-cli-role
  name: aws-cli